### ISSUE TITLE
No audio from Stepmania game (4B model)

### ISSUE THREAD

**Issue by Scott3377** [SpottyMatt/raspian-3b-stepmania-arcade#12]
Hi Matt,

Thanks for all your work on this! I am having an issue where I cannot get audio from the Stepmania game to play , but I am able to get audio from the Pi through the TV by running `aplay /usr/share/sounds/alsa/Front_Center.wav`. Audio also works when using VLC media player to play any of the included DDR songs. I have the Pi connected to a TV via HDMI, and I am using a Canakit package for the Pi (4b model). The TV is connected to HDMI 0. HDMI 1 was not showing video for some reason when it was connected to that mini-HDMI port.

Note: I am not using a USB audio card, but just the built-in alsa sound card that comes with the Raspberry Pi 4b.

Here's the output of aplay -l if that's at all helpful:
```
pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 2: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 6/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 2: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
Here is OS version info as well:
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
```
Thanks!

**Comment by SpottyMatt** [comment]
Are you hoping to get audio over HDMI through whatever CanaKit peripheral you've got, _or_ are you hoping to get audio out of the built-in jack on the 4B (and then presumably run it to a speaker or something)?

Those are very different rabbitholes to go down.

_Disclaimer:_ this _sounds_ (eh? eh?) like just a "configure audio on Raspberry Pi 4B" issue and not anything specifically related to StepMania, so I'm not sure how much I'll be able to help.

**Comment by Scott3377** [comment]
Ideally audio would work out of the box with the default Pi sound card and an HDMI into my TV. I can buy a USB soundcard if that's the easier route to go. The Canakit doesn't have any supplemental audio peripheral just the sound card that comes with the Pi. I just thought that since I can get quality audio working through the the HDMI with other applications (VLC Media player) that Stepmania should work the same. I wasn't sure if there was some competing application resource for the sound card that was preventing Stepmania from accessing audio. Any thoughts on best next steps for working audio?

**Comment by SpottyMatt** [comment]
The reason for USB audio is

1. Raspi 3B/3B+ can't output audio with high-enough quality over the built-in audio hardware for StepMania
2. Every Pi has USB ports, so only one configuration must be maintained in the repo
3. Keeping audio separate from HDMI makes it easier for folks to connect external speakers/sound systems in arcade-style cabinets

The question is "can the Raspi 4B output audio well enough for StepMania, using its built-in hardware?"

The easy way to test this would be to install the arcade per the instructions in this repo, then.

1. Run `sudo rm /etc/modprobe.d/usb-audio-by-default.conf` to un-disable other audio devices
2. Run `rm ~/.asoundrc` to un-configure USB audio
3. Reboot the Pi
4. Use the GUI sound settings board to select onboard audio
5. Plug in a regular speaker
6. Run StepMania and play through one entire song - is the audio clear or hideously distorted?

If the audio is hideously distorted, then the 4B needs USB audio; go buy one of the recommended cards.

If the audio is clear - excellent! The Pi 4B can use built-in audio! You can either stay with the built-in Audio jack or try HDMI. Ideally, you _should_ be able to just use the GUI audio setting panel to select HDMI audio output and save that as the default.
