### ISSUE TITLE
Why not use a PS1 Emulator in Lakka, RecalBox or Retropie with Dance Dance Revolution?

### ISSUE THREAD

**Issue by mtoensing** [SpottyMatt/raspian-3b-stepmania-arcade#17]
I don't understand why a native Raspberry Pi binary struggles with the on-board sound over HDMI and the speed of the Raspberry. I can use a PSX emulator, and it works over HDMI and a resonable speed. Why does stepmania on a pi have problems here?

Even my original modded XBOX 1 (!) runs Stepmania in full speed. Where is the bottleneck?

**Comment by wparad** [comment]
It worked for me, no problems (rpi 4B), counter to the docs here.

**Comment by mtoensing** [comment]
Can't reach solid 60 fps even with overclocking, low resolution and any other tweak I found. Emulation runs better. I asked why this is the case here: https://github.com/stepmania/stepmania/issues/2079

**Comment by mtoensing** [comment]
Ok, this works and is really fast (60 fps on most songs)

https://github.com/mtoensing/Moondance-StepMania64-pi4

**Comment by SpottyMatt** [comment]
I know we're all dying for a StepMania forum to talk about things, but... 

# Why not use (something other than an RPi)

![tenor](https://user-images.githubusercontent.com/7367949/225654418-89776ecd-b2b4-4132-96fe-8c3152570263.png)

It's definitely not the most-powerful Dance Game platform.

# Why HDMI Struggle

I don't know, man, HDMI & video standards are blacker magic than even most Linux development. I suppose each combination of binary + pi + HDMI cable + HDMI device might play out differently. I wasn't able to get a reliably-working combination with anything I had on hand. I guess I should update the README to be less-absolute about how it won't work. But I couldn't get it to.

# Why StepMania Have Problems (in general)

As @mtoensing found, StepMania is actually old. There are a couple derivative and/or successor projects (some run by the same SM devs!) - like moondance - that have more-modern codebases that'll probably work better.

They didn't exist when I started out wanting a dance game on a pi!

Also, the arcade uses StepMania 5.1 - which isn't even the newest 5.3. This was for plugin and feature compatibility... *when I started out on this project!*

Newer SM releases might work better; you *can* (in theory) use this project's toolchain to install SM 5.3 by overriding several make variables on the command-line but work hasn't been done to make that easy; the arcade repo is intended as a zero-config; JustWorks; predictable thing.
