### ISSUE TITLE
make missing opperand

### ISSUE THREAD

**Issue by Ramen508** [SpottyMatt/raspian-3b-stepmania-arcade#19]
I have cloned the repository then when I run make it says that I have a missing operand.

When I run makefile in geany it says shell not found.

im on a fresh 64 bit image on a pi4b

**Comment by Ramen508** [comment]
i just tried on a fresh 32 bit image and I had the same issue

**Comment by dflateau** [comment]
Also having the same problem trying to make in the directory:

readlink: missing operand

**Comment by hverdonk** [comment]
Same issue, fresh install of Raspberry Pi OS (Bullseye, 64 bit) on a model 3B. I've pasted the full output of `make` below:

```
dancer@raspberrypi:~/raspbian-stepmania-arcade $ make
git submodule init rpi-hw-info
Submodule 'rpi-hw-info' (https://github.com/SpottyMatt/rpi-hw-info.git) registered for path 'rpi-hw-info'
git submodule update rpi-hw-info
Cloning into '/home/dancer/raspbian-stepmania-arcade/rpi-hw-info'...
Submodule path 'rpi-hw-info': checked out '2059a7aea7c5081e9179bada2c6d6cc35e055cac'
make Makefile
make[1]: Entering directory '/home/dancer/raspbian-stepmania-arcade'
readlink: missing operand
Try 'readlink --help' for more information.
make[1]: Nothing to be done for 'Makefile'.
make[1]: Leaving directory '/home/dancer/raspbian-stepmania-arcade'
make all
make[1]: Entering directory '/home/dancer/raspbian-stepmania-arcade'
readlink: missing operand
Try 'readlink --help' for more information.
make system-prep
make[2]: Entering directory '/home/dancer/raspbian-stepmania-arcade'
readlink: missing operand
Try 'readlink --help' for more information.
chmod a+x ./merge-config.sh
sudo ./merge-config.sh ./performance-tune/raspi--tune.config /boot/config.txt
ERROR: [./performance-tune/raspi--tune.config] does not exist.
make[2]: *** [Makefile:44: system-prep] Error 1
make[2]: Leaving directory '/home/dancer/raspbian-stepmania-arcade'
make[1]: *** [Makefile:37: all] Error 2
make[1]: Leaving directory '/home/dancer/raspbian-stepmania-arcade'
make: *** [Makefile:24: all] Error 2
```

**Comment by SpottyMatt** [comment]
@hverdonk , thank you for the output. ⌛

**Comment by SpottyMatt** [comment]
Hmm, *a* problem - which might be *the* problem - is indicated by

```
./performance-tune/raspi--tune.config
```

that's supposed to be one of these config files: https://github.com/SpottyMatt/raspbian-stepmania-arcade/tree/master/performance-tune but, looks like the PI type wasn't determined correctly.

The `readlink` output is probably a red herring from  https://github.com/SpottyMatt/raspbian-stepmania-arcade/blob/master/Makefile#L14 ; when you don't have stepmania installed __yet__, readlink will fail (but it should be failing silently; I should spruce that up so it doesn't do that to people #16 ).

I THINK the problem here is with `rpi-hw-info`. @hverdonk , could you go to https://github.com/SpottyMatt/rpi-hw-info , clone it and run it on your Pi, and

1. if it fails to correctly report a `3B`, open an issue in that repo
2. if it correctly reports a `3B`, let me know here

**Comment by hverdonk** [comment]
Thanks for looking into this! Your hunch seems correct - running `rpi-hw-info.py` gave back an error message instead of a model number. I'll open an issue in the other repo with more information.

**Comment by dflateau** [comment]
Is there a suggested work-around in the meantime>

**Comment by SpottyMatt** [comment]
This should be updated in `master` now ( https://github.com/SpottyMatt/raspbian-stepmania-arcade/commit/b7fa6bbc882557d63dcb18300f7c988605bc60a6 ) , please update your local repo and try again.

**Comment by Ramen508** [comment]
I hope that I am am more helpful this time around. It seems like there is a link that is now returning a 404. Here is a copy of what I'm seeing:

blue@raspberrypi:~/raspbian-stepmania-arcade $ make
git submodule init rpi-hw-info
Submodule 'rpi-hw-info' (https://github.com/SpottyMatt/rpi-hw-info.git) registered for path 'rpi-hw-info'
git submodule update rpi-hw-info
Cloning into '/home/blue/raspbian-stepmania-arcade/rpi-hw-info'...
Submodule path 'rpi-hw-info': checked out '10b16f95686ef973aa3757e2826db5122a9bf519'
make Makefile
make[1]: Entering directory '/home/blue/raspbian-stepmania-arcade'
readlink: missing operand
Try 'readlink --help' for more information.
make[1]: Nothing to be done for 'Makefile'.
make[1]: Leaving directory '/home/blue/raspbian-stepmania-arcade'
make all
make[1]: Entering directory '/home/blue/raspbian-stepmania-arcade'
readlink: missing operand
Try 'readlink --help' for more information.
make system-prep
make[2]: Entering directory '/home/blue/raspbian-stepmania-arcade'
readlink: missing operand
Try 'readlink --help' for more information.
chmod a+x ./merge-config.sh
sudo ./merge-config.sh ./performance-tune/raspi-4b-tune.config /boot/config.txt
Merging configuration:
	Source : ./performance-tune/raspi-4b-tune.config
	Target : /boot/config.txt
dtoverlay=vc4-fkms-v3d
	~ Updated line in /boot/config.txt:
		Old : dtoverlay=vc4-kms-v3d
		New : dtoverlay=vc4-fkms-v3d
boot_delay=2
	o Already set!
gpu_mem=384
	o Already set!
max_usb_current=1
	o Already set!
sudo cp -fv ./system-prep/usb-audio-by-default.conf /etc/modprobe.d/.
'./system-prep/usb-audio-by-default.conf' -> '/etc/modprobe.d/./usb-audio-by-default.conf'
[ -e "/home/blue/.asoundrc" ] && rm "/home/blue/.asoundrc" || true
sudo apt-get update
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian bullseye-updates InRelease                  
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease   
Hit:4 http://archive.raspberrypi.org/debian bullseye InRelease                 
Reading package lists... Done                              
sudo apt-get install -y \
	unclutter
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
unclutter is already the newest version (8-25).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
sudo apt-get autoremove -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
make[2]: Leaving directory '/home/blue/raspbian-stepmania-arcade'
make stepmania-install
make[2]: Entering directory '/home/blue/raspbian-stepmania-arcade'
readlink: missing operand
Try 'readlink --help' for more information.
curl --location --fail "https://github.com/SpottyMatt/raspbian-stepmania-deb/releases/download/v5.1.0-b2/stepmania-4b_5.1.0-b2_bullseye.deb" > /tmp/stepmania.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
make[2]: *** [Makefile:55: stepmania-install] Error 22
make[2]: Leaving directory '/home/blue/raspbian-stepmania-arcade'
make[1]: *** [Makefile:38: all] Error 2
make[1]: Leaving directory '/home/blue/raspbian-stepmania-arcade'
make: *** [Makefile:24: all] Error 2

**Comment by hverdonk** [comment]
@Ramen508 the issue is that there's no precompiled deb file for the latest Raspberry Pi OS. I'll open an issue in the appropriate repo.

In the meantime, you have two options:
1. Downgrade your OS to Buster. This worked smoothly for me, and I've successfully installed Stepmania
2. Build the deb yourself following these instructions: https://github.com/SpottyMatt/raspbian-stepmania-deb. This option is more stable in the long term, but I had a bit of trouble getting it to work for some reason. If you do this and succeed, please do us all a solid and open a pull request over in that repo with the fresh deb.
