### ISSUE TITLE
Dear SpottyMatt,

### ISSUE THREAD

**Issue by clarakim1** [SpottyMatt/raspian-3b-stepmania-arcade#5]
I  appreciate  your great work.
Now I am trying to install Raspbian-3B-stepmania-arcade with my PIU mat.

I can see PIU mat usb dev with lsusb command in terminal screen.
But when I start stepmania,  only keyboard device and mouse device are working.

I am not sure if I have to make keymap.ini or something.

Can you help me?
Thank you in advance and hope to see your answer soon.

Bye!:)

**Comment by SpottyMatt** [comment]
How does the mat connect to the Pi? Does it use USB?

When the mat is connected, are you able to use it with StepMania?

If the mat doesn't work with StepMania at all, that's a hardware/software/driver problem. That probably has nothing to do with StepMania, and I cannot help.

You only need to create Keymaps by hand if you have more than one controller *and* the controllers are different.

**Comment by clarakim1** [comment]
Dear SpottyMatt,

Thank you!  And your answer is really helpful.
May I ask you one more question?
I found my usbdev  ID name is  0d2f:0001 and the company name is Andamiro Pump it Up!

And I made an ini file with   /usr/local/stepmania-5.1/Save/Keymaps/0-0d2f:0001.ini  

But still PIU mat USB device is not recognized in  stepmania program at all.

Best regards,
Clara

**Comment by SpottyMatt** [comment]
`/Keymaps/*.ini` do not do anything unless you have more than one controller. There's no need for a `Keymaps/*.ini` file if you only have one controller. StepMania's built-in key mapping will work just fine with a single controller.

Connect a keyboard to the Pi, navigate to StepMania's options -> input menu, and try to map the pad's inputs using StepMania.

If *that* does not work, then StepMania just doesn't recognize signals from your pad. That might be a problem with the pad, or a driver problem on your RaspberryPi.

**Comment by clarakim1** [comment]
Dear SpottyMatt

Thank you for your answer. That’s really kind of you.
Now I understand what is going on and my friend suggest that I can use other devices like joysticks or something to use my pad.
So, I would try to find out. I will tell you about this work soon.
Many Thanks for your great assistance in this project.

Most Sincerely,
Clara Kim

https://blog.naver.com/jesusofjeju/221490323740
https://blog.naver.com/kimyongim/221483736797

I am working for the kids, too
I hope I can make a stepmania game for kids with this song.

https://youtu.be/Kz-x7dMUeX8

Fortunately, I already made this with my MAC book.
Hopefully, I would like to make with Raspberry PI, too.

**Comment by clarakim1** [comment]
Dear Spotty,  

Can I as you another question about Audio?

options snd_usb_audio index=0
options snd_soc_core index=1
options snd_bcm2835 index=2

options snd slots=snd_usb_audio,snd_soc_core,snd_bcm2835

In this file, I changed audio index=0  to 1 to use analog jack.
Is it okay?
Thank you in advance!

most regards,
- Clara

**Comment by clarakim1** [comment]
Dear SpottyMatt,

Successfully, I can play stepmania with your tutorial!
Thank you Spotty, have a blessed day!

Clara
