### ISSUE TITLE
Verify and/or add Raspi4 support

### ISSUE THREAD

**Issue by SpottyMatt** [SpottyMatt/raspian-3b-stepmania-arcade#7]
This should work on Raspi4 platforms running Raspbian Buster or later.

Rename the repo to `raspiban-stepmania-arcade` when done _or_ create a new `raspi-4-stepmania-arcade`, depending.

While it's unlikely that new tech & updates will be built for Raspi 3 platforms (so maybe it's ok to just "move on" from Raspi 3 support), the embedded-device-ness of the Raspis means there may be folks trying to use Raspi 3 platforms for a very long time.

**Comment by SpottyMatt** [comment]
Did this in #8.

**Comment by Workshopshed** [comment]
Just installing on a pi4 and used the buster+desktop only image. Running make seems to have a dependency on Wolfram. Is that correct?

> Selecting previously unselected package wolframscript.
> Preparing to unpack .../15-wolframscript_1.3.0+2019062801_armhf.deb ...
> Unpacking wolframscript (1.3.0+2019062801) ...
> Selecting previously unselected package wolfram-engine.
> Preparing to unpack .../16-wolfram-engine_12.0.1+2019062401_armhf.deb ...
> wolfram-eula license has already been accepted
> Unpacking wolfram-engine (12.0.1+2019062401) ...

**Comment by SpottyMatt** [comment]
That's likely happening as part of the [`apt-get update`](https://github.com/SpottyMatt/raspbian-stepmania-arcade/blob/cdd3467d7f2b7593639d9d66000ad80c1fd6e171/Makefile#L47) that happens before installation (as a matter of hygiene). `wolfram-engine` and `wolframscript` seem to be bundled with the Raspbian desktop.

If you `apt install aptitude`, you can then run `aptitude why wolfram-engine --show-summary` and you'll see that _nothing_ depends on it - it's a top-level package that was installed.

**Comment by Workshopshed** [comment]
I'll double check but I thought it was:
sudo apt-get install --fix-broken -y /tmp/stepmania.deb

**Comment by Workshopshed** [comment]
I've run aptitude

```
pi@dancepi:~ $ aptitude why wolfram-engine --show-summary
Packages requiring wolfram-engine:
  stepmania-4b
pi@dancepi:~ $ aptitude why wolfram-engine --show-deps
i   stepmania-4b Depends wolfram-engine (>= 12.0.1+2019062401)

```

**Comment by SpottyMatt** [comment]
Oh interesting.

I'll dig into that.
